### ISSUE TITLE
BART-Large

### ISSUE THREAD

**Issue by chijames** [SALT-NLP/Structure-Aware-BART#4]
Hi,

I notice that in one earlier [paper](https://www.aclweb.org/anthology/2020.emnlp-main.336.pdf) of yours, the decoder is BART-large, which leads to much better performance.
Have you tried using BART-large in this paper?  If not, why?

Thanks.

**Comment by jiaaoc** [comment]
I did not use BART-large for this work because of the limited GPU memory size.
