### ISSUE TITLE
ADSC dataset

### ISSUE THREAD

**Issue by chijames** [SALT-NLP/Structure-Aware-BART#6]
Hi,

I tried several runs of the S-BART w. Discourse&Action (last row of Table 2) on the SAMSum dataset, and the results are sometimes higher/lower than the BART baseline, which is probably caused by random seeds. Nevertheless, the performance gain on the ADSC dataset seems to be more substantial according to Table 3. I was wondering if it's possible to also release the code to test the model on that dataset?

Thanks.

**Comment by jiaaoc** [comment]
You could directly use your trained models to evaluate on ADSC.

**Comment by jiaaoc** [comment]
And the same way to extract the discourse graphs/action graphs

**Comment by chijames** [comment]
Is it possible that you still have the processed files and can upload them to Google drive?

**Comment by jiaaoc** [comment]
I might not keep those files, let me check.

**Comment by jiaaoc** [comment]
Sorry, i did not keep those files. But they should be easy to be generated following what you did on SAMSum.

**Comment by chijames** [comment]
ok, thanks.

**Comment by chijames** [comment]
Sorry to reopen this, but there are 5 summaries per dialogue in the ADSC dataset, may I know which one is used for evaluation?

**Comment by chijames** [comment]
Sorry to reopen this, but there are 5 summaries per dialogue in the ADSC dataset, may I know which one is used for evaluation?

**Comment by jiaaoc** [comment]
I think I used the first one.
