### ISSUE TITLE
How to batch training samples?

### ISSUE THREAD

**Issue by Hannibal046** [SALT-NLP/Structure-Aware-BART#8]
Hello,
Thanks for the nice paper and code!
I notice that the decoder attends to every utterances after bart encoder. So I am wondering how to batch these, since the input to the model is`List[torch.Tesnor]` where `len(list)=batch_size, torch.Tensor.shape=[num_utts_in_one_conversation, seq_len]`?

In your code
```python
loss_tensors = self._step(batch) # in SummarizationModule/train_step
outputs = self(src_ids, attention_mask=src_mask, decoder_input_ids=decoder_input_ids, use_cache=False, discourse_graph = self.hparams.discourse_graph, adj = adj, segmented_encoder = self.hparams.segmented_encoder, relation = self.hparams.relation, action_adj = action_adj, actions = actions, actions_mask = actions_mask,) # in SummarizationModule/_step
```
But it seems that `BaseTransformer` does not give `forward` or` train_step` or` __call__` function? 
Thanks for your help

**Comment by jiaaoc** [comment]
You could refer to the codes of models here: https://github.com/GT-SALT/Structure-Aware-BART/blob/main/transformers/src/transformers/modeling_bart.py

**Comment by Hannibal046** [comment]
Hello,
the code you mentioned accepts inputs of shape `[batch_size,max_seq_len_in_a_batch]`, but your paper seems to get inputs of shape `[batch_size,max_num_utts_in_a_batch,max_seq_len_in_a_conv]`, did you pad all instances in a batch to the same `num_utts` and same `seq_len`, or just a for loop ? 
thanks so much!

**Comment by jiaaoc** [comment]
I think i have padded them into the same seq_len.

"[batch_size,max_num_utts_in_a_batch,max_seq_len_in_a_conv]", this should be for the discourse graph encoders.
