### ISSUE TITLE
Trained model for download

### ISSUE THREAD

**Issue by lakshmi-imrsv** [SALT-NLP/Structure-Aware-BART#9]
Hi
I would like to use S-Bart to generate summary for my own data.
Is the trained S-Bart model available for download ?

**Comment by jiaaoc** [comment]
I don't remember if I have uploaded the trained model to the link (https://drive.google.com/file/d/1EnBvGlhkyLx0N7tjlZPTt1pbgmiQO1Mm/view). If not, you might need to follow the steps to train the S-Bart model first.
